name: Field Level Security Change Alert
on:
 push:
   branches:
     - main
     - Int
     - Uat
   paths:
     - 'profiles/*.profile'
     - 'permissionsets/*.permissionset'
 pull_request:
   branches:
     - main
     - Int
     - Uat
   paths:
     - 'profiles/*.profile'
     - 'permissionsets/*.permissionset'
jobs:
 send-alert:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
         fetch-depth: 0  # Fetch full history
         fetch-tags: false
     - name: Check for FLS changes on target fields
       id: fls_check
       shell: bash
       run: |
         set -euo pipefail
         # Initialize variables
         FLS_CHANGED=false
         CHANGED_FIELDS=""
         TARGET_FIELD="testing_of_the_git_alert__c.testing_of_the_git_alert__c"
         # Avoid weird quoting/escaping for non-ASCII paths
         git config --global core.quotepath false
         # Determine commit range based on event type
         if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           # For PR events: compare PR branch with target branch
           echo "PR event detected: Comparing ${{ github.head_ref }} with ${{ github.base_ref }}"
           BEFORE_COMMIT="origin/${{ github.base_ref }}"
           CURRENT_COMMIT="${{ github.sha }}"
         else
           # For push events: use standard commit comparison
           if git cat-file -e "${{ github.event.before }}" 2>/dev/null; then
             echo "Using commit range: ${{ github.event.before }}..${{ github.sha }}"
             BEFORE_COMMIT="${{ github.event.before }}"
           else
             echo "Before commit not found, using HEAD~1"
             BEFORE_COMMIT="HEAD~1"
           fi
           CURRENT_COMMIT="${{ github.sha }}"
         fi
         # Fetch the target branch for PR comparisons
         if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           git fetch origin "${{ github.base_ref }}"
         fi
         # Collect only .profile/.permissionset files changed in this range
         CHANGED_FILES="$(git diff --name-only "$BEFORE_COMMIT" "$CURRENT_COMMIT" \
           | grep -E '^(profiles/.*\.profile|permissionsets/.*\.permissionset)$' || true)"
         echo "Changed files:"
         echo "${CHANGED_FILES:-<none>}"
         # Scan each changed file
         if [[ -n "${CHANGED_FILES}" ]]; then
           while IFS= read -r FILE; do
             [[ -z "$FILE" ]] && continue
             echo "Checking file: $FILE"
             # Check for field presence in the diff (both added and removed)
             if git diff "$BEFORE_COMMIT" "$CURRENT_COMMIT" -- "$FILE" | grep -E "(fieldPermissions>.*$TARGET_FIELD|$TARGET_FIELD.*fieldPermissions>)" > /dev/null; then
               echo "Found field change in: $FILE"
               FLS_CHANGED=true
               # Capture the specific change type
               if git diff "$BEFORE_COMMIT" "$CURRENT_COMMIT" -- "$FILE" | grep -E ">$TARGET_FIELD<" > /dev/null; then
                 CHANGE_TYPE="ADDED/MODIFIED"
               else
                 CHANGE_TYPE="REMOVED"
               fi
               CHANGED_FIELDS+="- $TARGET_FIELD ($CHANGE_TYPE) in $FILE"$'\n'
             fi
           done <<< "$CHANGED_FILES"
         fi
         echo "FLS_CHANGED=$FLS_CHANGED"
         echo "FLS_CHANGED=$FLS_CHANGED" >> "$GITHUB_OUTPUT"
         echo "CHANGED_FIELDS<<EOF" >> "$GITHUB_OUTPUT"
         echo "$CHANGED_FIELDS" >> "$GITHUB_OUTPUT"
         echo "EOF" >> "$GITHUB_OUTPUT"
     - name: Send alert email
       if: steps.fls_check.outputs.FLS_CHANGED == 'true'
       uses: dawidd6/action-send-mail@v3
       with:
         server_address: smtp.gmail.com
         server_port: 465
         username: ${{ secrets.EMAIL_USERNAME }}
         password: ${{ secrets.EMAIL_PASSWORD }}
         subject: "Field Level Security Change Alert - ${{ github.event_name }} on ${{ github.ref_name }}"
         to: sathishnallapula@gmail.com,kanumalamanoj@gmail.com,prashkulkarni7064@gmail.com,concaku@partner.waters.com,conplax@partner.waters.com
         from: sathishnallapula@gmail.com
         body: |
           Attention:
           A field-level security change has been detected!
           Event Type: ${{ github.event_name }}
           Branch: ${{ github.ref_name }}
           Changes detected:
           ${{ steps.fls_check.outputs.CHANGED_FIELDS }}
           Details:
           Repository: ${{ github.repository }}
           Commit: ${{ github.sha }}
           Author: ${{ github.actor }}
           Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
           Please review the changes immediately.
           Regards,
           GitHub Actions
