name: Field Level Security Change Alert

on:
  push:
    branches:
      - main
      - Int
      - Uat
    paths:
      - 'profiles/*.profile'
      - 'permissionsets/*.permissionset'
  pull_request:
    branches:
      - main
      - Int
      - Uat
    paths:
      - 'profiles/*.profile'
      - 'permissionsets/*.permissionset'

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history
          fetch-tags: false

      - name: Check for FLS changes on target fields
        id: fls_check
        shell: bash
        run: |
          set -euo pipefail

          # Initialize flag
          FLS_CHANGED=false

          # Avoid weird quoting/escaping for non-ASCII paths (spaces are fine either way)
          git config --global core.quotepath false

          # Determine commit range based on event type
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PR events: compare with target branch
            echo "PR event detected: Comparing with ${{ github.base_ref }}"
            BEFORE_COMMIT="origin/${{ github.base_ref }}"
            git fetch origin "${{ github.base_ref }}"
          else
            # For push events: use standard commit comparison
            if git cat-file -e "${{ github.event.before }}" 2>/dev/null; then
              echo "Using commit range: ${{ github.event.before }}..${{ github.sha }}"
              BEFORE_COMMIT="${{ github.event.before }}"
            else
              echo "Before commit not found, using HEAD~1"
              BEFORE_COMMIT="HEAD~1"
            fi
          fi

          # Collect only .profile/.permissionset files changed in this range (newline-separated)
          CHANGED_FILES="$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}" \
            | grep -E '^(profiles/.*\.profile|permissionsets/.*\.permissionset)$' || true)"

          echo "Changed files:"
          echo "${CHANGED_FILES:-<none>}"

          # Scan each changed file; preserve spaces in filenames
          if [[ -n "${CHANGED_FILES}" ]]; then
            while IFS= read -r FILE; do
              [[ -z "$FILE" ]] && continue
              echo "Checking file: $FILE"

              if git diff "$BEFORE_COMMIT" "${{ github.sha }}" -- "$FILE" \
                | grep -E 'testing_of_the_git_alert__c\.testing_of_the_git_alert__c' > /dev/null; then
                echo "Found field change in: $FILE"
                FLS_CHANGED=true
                break
              fi
            done <<< "$CHANGED_FILES"
          fi

          echo "FLS_CHANGED=$FLS_CHANGED"
          echo "FLS_CHANGED=$FLS_CHANGED" >> "$GITHUB_OUTPUT"

      - name: Send alert email
        if: steps.fls_check.outputs.FLS_CHANGED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Field Level Security Change Alert - ${{ github.event_name }} on ${{ github.ref_name }}"
          to: sathishnallapula@gmail.com,kanumalamanoj@gmail.com,prashkulkarni7064@gmail.com,concaku@partner.waters.com,conplax@partner.waters.com
          from: sathishnallapula@gmail.com
          body: |
            Attention:

            A change has been detected on field-level security for the following fields:
            - testing_of_the_git_alert__c

            Please review the changes in the repository:
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Event Type: ${{ github.event_name }}
            Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            Regards,
            GitHub Actions
