name: Field Level Security Change Alert
 
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/*.profile'
      - 'permissionSets/*.permissionset'
 
jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history
 
      - name: Check for FLS changes on target fields
        id: fls_check
        run: |
          # Initialize flag
          FLS_CHANGED=false
          
          # Check if the before commit exists
          if git cat-file -e "${{ github.event.before }}" 2>/dev/null; then
            echo "Using commit range: ${{ github.event.before }}..${{ github.sha }}"
            BEFORE_COMMIT="${{ github.event.before }}"
          else
            echo "Before commit not found, using HEAD~1"
            BEFORE_COMMIT="HEAD~1"
          fi
          
          # Get list of changed .profile or .permissionset files
          CHANGED_FILES=$(git diff --name-only $BEFORE_COMMIT ${{ github.sha }} \
            | grep -E 'profiles/.*\.profile$|permissionSets/.*\.permissionset$' || true)
          
          echo "Changed files: $CHANGED_FILES"
          
          # Check each changed file for specific field permissions
          for FILE in $CHANGED_FILES; do
            echo "Checking file: $FILE"
            if git diff $BEFORE_COMMIT ${{ github.sha }} -- "$FILE" | \
              grep -E 'testing_of_the_git_alert__c\.testing_of_the_git_alert__c'; then
              echo "Found field change in: $FILE"
              FLS_CHANGED=true
              break
            fi
          done
          
          echo "FLS_CHANGED=$FLS_CHANGED"
          echo "FLS_CHANGED=$FLS_CHANGED" >> $GITHUB_OUTPUT
 
      - name: Send alert email
        if: steps.fls_check.outputs.FLS_CHANGED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Field Level Security Change Alert"
          to: sathishnallapula@gmail.com,kanumalamanoj@gmail.com,prashkulkarni7064@gmail.com,concaku@partner.waters.com,conplax@partner.waters.com,conyran@partner.waters.com,consnal1@partner.waters.com,conmkan2@partner.waters.com
          from: sathishnallapula@gmail.com
          body: |
            Attention:
 
            A change has been detected on field-level security for the following fields:
            - testing_of_the_git_alert__c
            
            Please review the changes in the repository:
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
 
            Regards,
            GitHub Actions
