name: Field Level Security Change Alert

on:
  push:
    branches:
      - main
    paths:
      - 'src/profiles/*.profile'
      - 'src/permissionSets/*.permissionset'

jobs:
  send-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for FLS changes on target fields
        id: fls_check
        run: |
          # Fetch the base and head of the push
          git fetch origin

          # Get list of changed .profile or .permissionset files across the entire push
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep -E 'src/profiles/.*\.profile$|src/permissionSets/.*\.permissionset$' || true)

          # Initialize flag
          FLS_CHANGED=false

          # Check each changed file for specific field permissions
          for FILE in $CHANGED_FILES; do
            if git diff ${{ github.event.before }} ${{ github.sha }} -- "$FILE" | \
              grep -E 'Unit_Sale_Price__c|Total_Net_Value__c'; then
              FLS_CHANGED=true
              break
            fi
          done

          # Export output so the next step can read it
          echo "FLS_CHANGED=$FLS_CHANGED" >> $GITHUB_OUTPUT

      - name: Send alert email
        if: steps.fls_check.outputs.FLS_CHANGED == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Field Level Security Change Alert"
          to: sathishnallapula@gmail.com,kanumalamanoj@gmail.com,prashkulkarni7064@gmail.com
          from: ${{ secrets.EMAIL_FROM }}
          body: |
            Attention:

            A change has been detected on field-level security for the following fields:
            - Unit_Sale_Price__c
            - Total_Net_Value__c

            Please review the changes in the repository:
            ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            Link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            Regards,
            GitHub Actions
